version: '3.8'

services:
  php:
    build:
      context: .
    volumes:
      - ./:/var/www/html


  web:
    image: nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

